### ISSUE TITLE
Privacy Policy Doesn't Look Right

### ISSUE THREAD

**Issue by LautaroLobo12** [caravanapp-ca/caravanapp-ca#42]
Hi! 

The Privacy Policy page has no header, and no margin/padding whatsoever. So it looks like s#¡t. 

How to fix this? Well... using the about.tsx file as an example, I was able to make it look nicer, but unable of make the inline links to work, because it's all strings so it just prints the HTML without rendering it properly.

So, the other way. Using just plain Typescript style, you know, moving all the text and HTML stuff inside the return statement. I want to do this. But, I won't start working on it until someone gives me the 'you go' sign. Maybe there's a better idea or something.

_waiting for the you go sign_

**Comment by quinnturner** [comment]
Definitely go ahead with updating the styling!

To be honest, I don't recommend following `About.tsx`. The approach that was taken heavily restricts styling since it's all in one `<Typography>` styling. However, it can still work. The `children` prop in Typography might accept a `React.ReactNode` (...checks, it does!). Since it accepts a React.ReactNode, you an do something like passing in a [material-ui Link](https://material-ui.com/components/links/) `<Link href="/link" color="primary" target="_blank" rel="noopener">text here</Link>` in the array. I'd expect that to work.

My favourite modern way of doing this sort of page is to use something like [MDX](https://mdxjs.com/getting-started/create-react-app). However, that is adding a dependency, and might not be the easiest approach. I'd accept a PR if that was done, but it may cause more headaches.

Side note, I note that the privacy page is blocked behind onboarding: https://github.com/caravanapp-ca/caravanapp-ca/blob/master/packages/web/src/App.tsx#L271 . Consider removing the `forceOnboarding`, since we really don't need to there 😄

**Comment by quinnturner** [comment]
The "best" way using the current tech stack is still probably the approach taken on that page (with divs, headers, etc.), just with the updated material-ui styling.

**Comment by LautaroLobo12** [comment]
Okay, thanks, working on it!

**Comment by LautaroLobo12** [comment]
https://ibb.co/bBvJv7K
https://ibb.co/JdP7BLq

First one or second one? 

The first one has one Typography element for each wall of text and one Typography element for each heading.
The second one is the good ol' Privacy Policy HTML wrapped up inside one Typography element.

If necessary, we can discuss further details in the PR... but I should first decide which one to PR :sweat_smile:

**Comment by quinnturner** [comment]
Both look great, choose whichever one you like better 🙂

**Comment by quinnturner** [comment]
PR #43
